---
title: Group
output:
  html_document:
    self_contained: false
---
### Some group photos and memories (to come soon..)

```{=html}
<iframe src="./group_pics.html" title="Quarto revealjs Documentation" style="height: 400px; width: 100%"></iframe>

```

### Current

#### PhD 

- Rishiraj Adhikary (July 2019 - present)
- Zeel Patel (Jan 2020 - present)
- Rishab Mondal (June 2023 - present)
- Khush Shah (July 2023 - present)

#### MTech

- Suraj Jaiswal (July 2022 - present)
- Ayush Srivastava (July 2022 - present)

#### BTech

- Dhruv Patel (BTech 2024)
- Haikoo Khandor (BTech 2024)
- Progyan Das (BTech 2024)
- Madhav Kanda (BTech 2024)
- Aditi Agarwal (BTech 2024)
- Utkarsh Mittal (BTech 2024)


### Alumni


#### BTech

- Aadesh Desai (BTech 2023): MS at CMU
- Eshan Gujarathi (BTech 2023): Predoc at IIT Madras
- Gautam Vasistha (BTech 2023): Data Scientist as Skan.AI
- Hitarth Gandhi (BTech 2023): 
- Saagar Parikh (BTech 2023): MS at CMU
- Xhitij Choudhary (BTech 2023): Data Scientist at Skan.AI
- Chris Francis (BTech 2022): MS at UCSD
- Dhruvi Lodhavia (BTech 2022): MS at UCSD
- Hetvi Shastri (BTech 2022): PhD at UMass Amherst
- Harsh Patel (BTech 2022): MS at UCSD
- Palak Purohit (BTech 2022): MS at Caltech
- Shivam Sahni (BTech 2022): MS at UCSD
- Apoorv Agnihotri (BTech 2020): First job at Wadhwani AI -> Data Scientist at Rephrase.ai
- Deepak Narayanan (BTech 2020): First job at Microsoft Research India -> MS at ETH Zurich
- Kukunuri Rithwik (BTech 2020): First job at Jio -> Data Scientist at Nykaa
- Soham Pachpande (BTech 2020): First job at  HSBC-> MS at UCSD -> SWE at Salesforce

#### MTech

- Ankita Jain (MTech 2022): First job at Oracle
- Karan Kumar (MTech 2020): First job at Trading Technologies
- Souvik Roy (MTech 2020): First job at eClerx

#### Research Assistant

- Kaushal Modi
- Prerna Khanna: Now a PhD student at Stony Brook
- Tanmay Srivastava: Now a PhD student at Stony Brook
- Rohit Patil: First job at Publicis Sapient

### Outside IITGn Interns

- Vibhuti Bansal (Summer 2022)
- Rohit Khoiwal (Summer 2022)
- Anand Hegde (Summer 2022)
- Shobhit Belwal (Summer 2022)
- Aryan Varshney (Summer 2022) 