"""A remote-friendly gallery of screenshots from the implemented pages."""
from pathlib import Path
from html import escape
HERE = Path(__file__).resolve().parent
styles = [('swiss','Swiss red','01-swiss-red.png'),('editorial','Warm editorial','02-warm-editorial.png'),('index','Scientific index','03-scientific-index.png'),('forest','Forest notebook','04-forest-notebook.png')]
pages = [('index','Home','index.html'),('teaching','Teaching','teaching.html'),('cheatsheets','Cheatsheets','teaching.html'),('teaching-videos','Video directory','teaching-videos.html'),('projects','Open source','projects.html')]
sections = []
for design, label, board in styles:
    for mode in ['light','dark']:
        cards = []
        for slug, title, file in pages:
            url = f'{file}?design={design}&mode={mode}' + ('#cheatsheets' if slug=='cheatsheets' else '')
            image = f'images/rendered/{design}-{mode}-{slug}.jpg' + ('?v=20261004-shared-swiss' if design=='swiss' else '')
            cards.append(f'<article><div class="card-title"><h3>{title}</h3><a href="{escape(url)}">Open page</a></div><a class="screenshot" href="{escape(url)}"><img src="{image}" alt="{label}, {mode} mode: {title}, rendered in the browser" loading="lazy" width="1440" height="1100"></a><a class="full-image" href="{image}">View full screenshot</a></article>')
        sections.append(f'<section data-design="{design}" data-mode="{mode}" aria-labelledby="{design}-{mode}"><header><h2 id="{design}-{mode}">{label} · {mode.title()}</h2><a href="images/{board}">Original homepage mockup</a></header><div class="pages">'+''.join(cards)+'</div></section>')
page = '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,follow"><title>Website previews · Nipun Batra</title><style>
*{box-sizing:border-box}body{margin:0;background:#f8f7f1;color:#252b26;font:15px/1.6 system-ui,sans-serif}main{max-width:1360px;padding:34px 24px 60px;margin:auto}h1{font-size:38px;line-height:1.15;letter-spacing:-.045em;margin:0 0 12px}p{color:#62675f;margin:0 0 24px;max-width:66ch}a{color:#a33228;text-underline-offset:4px}form{display:flex;gap:22px;flex-wrap:wrap;border-top:1px solid #d1d4ca;border-bottom:1px solid #d1d4ca;padding:17px 0;margin-bottom:24px}label{display:flex;gap:10px;align-items:center;font-size:13px}select{font:inherit;background:#fffefa;border:1px solid #b4bbaf;padding:9px;max-width:230px}section{padding:14px 0 35px}section>header{display:flex;align-items:baseline;justify-content:space-between;gap:20px;margin-bottom:16px}h2{font-size:24px;letter-spacing:-.03em;margin:0}.pages{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:28px}article{min-width:0}.card-title{display:flex;justify-content:space-between;align-items:baseline;gap:15px;margin-bottom:10px}.card-title a,.full-image,section>header>a{font-size:12px}h3{font-size:16px;margin:0}article:first-child .screenshot{aspect-ratio:auto}.screenshot{display:block;border:1px solid #d1d4ca;background:#e4e6dd;overflow:hidden;aspect-ratio:1440/1100}img{display:block;width:100%;height:auto;min-height:100%;object-fit:cover;object-position:top}.full-image{display:inline-block;margin-top:8px}[hidden]{display:none!important}:focus-visible{outline:2px solid #a33228;outline-offset:4px}@media(max-width:700px){main{padding:24px 18px}h1{font-size:31px}.pages{grid-template-columns:1fr}section>header{display:block}section>header>a{display:inline-block;margin-top:8px}form{gap:12px}label{justify-content:space-between;width:100%}select{width:210px}}
</style></head><body><main><h1>Website previews</h1><p>These are screenshots of the working pages. Choose a style and appearance, then open any page to try its links, search and filters.</p><form><label>Style <select id="design"><option value="swiss">1 · Swiss red</option><option value="editorial">2 · Warm editorial</option><option value="index">3 · Scientific index</option><option value="forest">4 · Forest notebook</option><option value="all">All four</option></select></label><label>Appearance <select id="mode"><option value="light">Light</option><option value="dark">Dark</option><option value="all">Both</option></select></label></form>SECTIONS</main><script>
const design=document.querySelector('#design'),mode=document.querySelector('#mode'),params=new URLSearchParams(location.search);for(const control of [design,mode])if([...control.options].some(o=>o.value===params.get(control.id)))control.value=params.get(control.id);function apply(){document.querySelectorAll('section[data-design]').forEach(section=>section.hidden=!((design.value==='all'||section.dataset.design===design.value)&&(mode.value==='all'||section.dataset.mode===mode.value)));const url=new URL(location);url.searchParams.set('design',design.value);url.searchParams.set('mode',mode.value);history.replaceState(null,'',url)}design.addEventListener('change',apply);mode.addEventListener('change',apply);apply();</script></body></html>'''
(HERE/'review.html').write_text(page.replace('SECTIONS',''.join(sections)))
print('Built gallery of 40 browser screenshots, each linked to its working page.')
